In [3]:
# perkalian matrix

import numpy as np
A = np.array([20, 45, 64])
B = np.array([22, 13, 79])

kali = A * B
print(kali)

[ 440  585 5056]


In [4]:
# pengurangan matrix

import numpy as np
A = np.array([20, 45, 64])
B = np.array([22, 13, 79])

kurang = A - B
print(kurang)

[ -2  32 -15]


In [6]:
# transpose matrix

import numpy as np
A = np.array([[20, 45, 64], [22, 13, 79]])

transpose_A = np.transpose(A)
print(transpose_A)

[[20 22]
 [45 13]
 [64 79]]


In [7]:
# nilai invers

import numpy as np
A = np.array([[20, 45], [13, 64]])

invers_A = np.linalg.inv(A)
print("\nInvers matriks A: ")
print(invers_A)


Invers matriks A: 
[[ 0.09208633 -0.0647482 ]
 [-0.01870504  0.02877698]]


In [8]:
# nilai determinan

import numpy as np
A = np.array([[20, 45], [13, 64]])

determinant_A = np.linalg.det(A)
print("\nNilai determinant: ")
print(determinant_A)


Nilai determinant: 
694.9999999999999
